kind: Build
apiVersion: builds.katanomi.dev/v1alpha1
spec:
  workspaces:
  - name: source
  tasks:
    ## read oss version
    - name: oss-version
      taskRef:
        kind: ClusterTask
        name: alauda-read-oss-version
      params:
      - name: version-file-path
        value: ".build/opensource-version"
      workspaces:
      - name: source
        workspace: source
    ## ko publish knative-operator image
    - name: build-operator
      taskRef:
        kind: ClusterTask
        name: alauda-ko-build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: verbose
          value: "false"
        - name: import-path
          value: "./cmd/operator"
        - name: container-image
          value: "build-harbor.alauda.cn/devops/knative.dev/operator/cmd/operator"
        - name: container-image-tag
          value: v$(tasks.oss-version.results.oss-version)-$(tasks.oss-version.results.commit-short-id)
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go:latest
    - name: build-webhook
      taskRef:
        kind: ClusterTask
        name: alauda-ko-build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: verbose
          value: "false"
        - name: import-path
          value: "./cmd/webhook"
        - name: container-image
          value: "build-harbor.alauda.cn/devops/knative.dev/operator/cmd/webhook"
        - name: container-image-tag
          value: v$(tasks.oss-version.results.oss-version)-$(tasks.oss-version.results.commit-short-id)
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go:latest
    - name: image-scan
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: trivy-image-scan
      workspaces:
        - name: source
          workspace: source
        - name: cache
      runAfter:
        - build-operator
        - build-webhook
      when: []
      params:
        - name: targets
          value:
            - $(tasks.build-operator.results.ociContainerImageBuild-url)
            - $(tasks.build-webhook.results.ociContainerImageBuild-url)
